---
- hosts: all
  tasks:
    - name: install httpd
      package: name=httpd state=installed
    - name: configure
      shell: "echo Welcome to Gagandeep Server v1 > /var/www/html/index.html"
    - name: start service
      service: name=httpd state=started
